
name: Build GARASI ABAH BONTOT APK

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'


      - run: flutter pub get


      - run: flutter analyze


      - run: flutter test
        continue-on-error: true


      - run: flutter build apk --release


      - uses: actions/upload-artifact@v4
        with:
          name: garasi-abah-bontot-apk
          path: build/app/outputs/flutter-apk/app-release.apk
